### ISSUE TITLE
[xla:cpu] use Intel AMX for int8 and bf16?

### ISSUE THREAD

**Issue by mattjj** [openxla/xla#10556]
Originally posted by @jchia on google/jax#20245:

>  Please consider supporting using Intel AMX for matrix multiplication involving matrix elements that are INT8 or BF16.

I think this is an ask for XLA:CPU.

**Comment by penpornk** [comment]
Since v0.4.21, JAX can use AMX for bf16 data type (through custom calls to the oneDNN library). AMX int8 support is coming in the next several months.

Here is an example matmul results on a 22-core Sapphire Rapids instance on GCP:

matmul.py (reports time for 10 matmuls)
```Python
import jax, timeit
from jax import random
import jax.numpy as jnp

n = 3000
dtype = jnp.bfloat16
key = random.key(0)
a = random.normal(key, (n, n), dtype)
b = random.normal(key, (n, n), dtype)

duration = timeit.timeit(
    lambda: jnp.dot(a, b).block_until_ready(), number=10)

print(duration, "seconds")
```

The program is significantly faster with JAX 0.4.21 because it could use AMX_BF16.
```sh
$ pip install --force-reinstall jax==0.4.20 jaxlib==0.4.20
$ python3 matmul.py
0.5513059509999039 seconds
$ pip install --force-reinstall jax==0.4.21 jaxlib==0.4.21
$ python3 matmul.py
0.1411043499997504 seconds
```

To verify oneDNN is actually using AMX, `export ONEDNN_VERBOSE=1` in the command line before running the code. Each matmul that is run in oneDNN will print a line that says what matmul implementation kernel it's using, the matmul size, runtime, etc.

### jaxlib 0.4.20
  * jaxlib 0.4.20 and older calls Eigen's tensor contraction for Dot. 
  * Eigen partitions the contractions into smaller cache-fitted chunks and call oneDNN's single-threaded f32 matmul for each chunk. So we see lots of matmuls (100+) with sizes like `120x304:304x240`, `144x304:304x240`, etc.
  * `gemm_api` means the classic dnnl_sgemm kernel is used, `src_f32`, `wei_f32` and `dst_f32` means all inputs/output are in f32.
```
$ export ONEDNN_VERBOSE=1
$ python3 matmul.py  
onednn_verbose,info,oneDNN v3.3.0 (commit N/A)
onednn_verbose,info,cpu,runtime:threadpool,nthr:11
onednn_verbose,info,cpu,isa:Intel AVX-512 with float16, Intel DL Boost and bfloat16 support and Intel AMX with bfloat16 and 8-bit integer support
onednn_verbose,info,gpu,runtime:none
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,exec,cpu,gemm_api,,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,120x304:304x240,31.3911
onednn_verbose,exec,cpu,gemm_api,,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,144x304:304x240,31.4399
onednn_verbose,exec,cpu,gemm_api,,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,144x304:304x240,31.479
onednn_verbose,exec,cpu,gemm_api,,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,144x304:304x240,31.5352
onednn_verbose,exec,cpu,gemm_api,,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,144x304:304x240,31.5342
onednn_verbose,exec,cpu,gemm_api,,undef,src_f32::blocked:ab:f0 wei_f32::blocked:ab:f0 dst_f32::blocked:ab:f0,,,144x304:304x240,31.564
...
```

### jaxlib 0.4.21
* Starting with v0.4.21, XLA:CPU directly calls oneDNN's matmul primitive for Dots. 
* We see exactly 10 lines for 10 oneDNN matmuls, each with size 3000x3000.
* `matmul,brg:avx512_core_amx` is used. This kernel can use AMX.
* Inputs and output have bf16 type.
```
$ export ONEDNN_VERBOSE=1
$ python3 matmul.py
onednn_verbose,info,oneDNN v3.3.0 (commit N/A)
onednn_verbose,info,cpu,runtime:threadpool,nthr:22
onednn_verbose,info,cpu,isa:Intel AVX-512 with float16, Intel DL Boost and bfloat16 support and Intel AMX with bfloat16 and 8-bit integer support
onednn_verbose,info,gpu,runtime:none
onednn_verbose,info,prim_template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx,undef,src_bf16::blocked:ab::f0 wei_bf16::blocked:ab::f0 dst_bf16::blocked:ab::f0,,,3000x3000:3000x3000,13.396
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx,undef,src_bf16::blocked:ab::f0 wei_bf16::blocked:ab::f0 dst_bf16::blocked:ab::f0,,,3000x3000:3000x3000,12.4141
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx,undef,src_bf16::blocked:ab::f0 wei_bf16::blocked:ab::f0 dst_bf16::blocked:ab::f0,,,3000x3000:3000x3000,11.6931
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx,undef,src_bf16::blocked:ab::f0 wei_bf16::blocked:ab::f0 dst_bf16::blocked:ab::f0,,,3000x3000:3000x3000,11.5771
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx,undef,src_bf16::blocked:ab::f0 wei_bf16::blocked:ab::f0 dst_bf16::blocked:ab::f0,,,3000x3000:3000x3000,11.7739
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx,undef,src_bf16::blocked:ab::f0 wei_bf16::blocked:ab::f0 dst_bf16::blocked:ab::f0,,,3000x3000:3000x3000,11.5391
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx,undef,src_bf16::blocked:ab::f0 wei_bf16::blocked:ab::f0 dst_bf16::blocked:ab::f0,,,3000x3000:3000x3000,11.687
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx,undef,src_bf16::blocked:ab::f0 wei_bf16::blocked:ab::f0 dst_bf16::blocked:ab::f0,,,3000x3000:3000x3000,11.5779
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx,undef,src_bf16::blocked:ab::f0 wei_bf16::blocked:ab::f0 dst_bf16::blocked:ab::f0,,,3000x3000:3000x3000,11.679
onednn_verbose,exec,cpu,matmul,brg:avx512_core_amx,undef,src_bf16::blocked:ab::f0 wei_bf16::blocked:ab::f0 dst_bf16::blocked:ab::f0,,,3000x3000:3000x3000,11.6631
```

**Comment by penpornk** [comment]
SGTM. Let's close the issue then. I can still post updates afterward. :)

**Comment by jchia** [comment]
Thanks. I notice that the `cpu,matmul,brg:avx512_core_amx` shows up only with n >= 204. Any smaller and it will be `cpu,gemm_api,`.

If code in some library somehow deciding whether to do matmul or gemm_api depending on the input size? On the AWS EC2 C7i.large I tested with at least, this decision turns out to be not beneficial with `n=203` clocking 0.041s and `n=204` clocking 0.014s, which is much faster. The situation with `jnp.matmul` is similar.

Any idea how it is decided whether to use `gemm_api` or `matmul,brg:avx512_core_amx`?

**Comment by penpornk** [comment]
@jchia

> I notice that the cpu,matmul,brg:avx512_core_amx shows up only with n >= 204. Any smaller and it will be cpu,gemm_api,.

Yes. Great catch!

> Any idea how it is decided whether to use gemm_api or matmul,brg:avx512_core_amx?

 This is done by a rough #flops threshold here:
https://github.com/openxla/xla/blob/54db31320b409cff93409a9df5f375ee0a7d0aba/xla/service/cpu/onednn_matmul_rewriter.cc#L370-L371

If there aren't enough #flops, XLA:CPU won't rewrite normal Dot ops to oneDNN matmul custom calls:
```
    2 * 203^3 < 2^24 < 2 * 204^3
don't rewrite <---|---> rewrite
```

This thresholding is just a quick heuristic based on some e2e model performance results and will continue to be improved. A better heuristic / cost model would take into account the shapes and data types as well. If you have suggestions, please feel free to contribute! :)

**Comment by jchia** [comment]
I don't have a better heuristic. Perhaps what's needed is just benchmarks on a lot of hardware but that would be expensive.

Or, a user-configurable threshold.

**Comment by jchia** [comment]
Does `matmul` take a meaningfully different code path than `dot` for the purpose of deciding whether to rewrite?

With the following sightly different program that uses `jnp.matmul` instead of `jnp.dot`, there was no ONEDNN_VERBOSE output no matter how large I set `m` to be, even 1000000. `m, n` of `1000000, 1` saw no output but `m, n` of only `1, 4` did. `m` mattered very little, if at all. Is this expected or the right behavior?

```
import jax
from jax import random
import jax.numpy as jnp
import os
import timeit

os.environ['XLA_FLAGS'] = ('--xla_force_host_platform_device_count=1')
jax.config.update('jax_platform_name', 'cpu')
m, n = 1000000, 1
#m, n = 1000, 1
#m, n = 1, 4
dtype = jnp.float32
key = random.key(0)
a = random.normal(key, (m, n, 64), dtype)
b = random.normal(key, (m, 64, n), dtype)

@jax.jit
def dot(x, y):
    return jnp.matmul(x, y)

# Warmup.
for _ in range(3):
    dot(a, b)

dot_duration = timeit.timeit(lambda: dot(a, b).block_until_ready(), number=3)

print(dot_duration, 'seconds')
```

I suppose that if the onednn_verbose log does not appear it means that rewriting did not happen.

Here are some observations of whether the onednn_verbose log appeared for some combinations of (m, n, dot-vs-matmul):
1000000, 1, matmul: no
1000000, 1, dot: segfault
1000, 1, matmul: no
1000, 1, dot: yes
1, 4, matmul: yes
1, 4, dot: yes

The 2 main observations are the different behavior of matmul and dot for large-enough m and the segfault.

**Comment by jchia** [comment]
I suppose the "1000000, 1, matmul" is not a big matmul but effectively 1000000 small matmuls, so AMX can't help with that.
