### ISSUE TITLE
Does Tensorflow XLA use MLIR?

### ISSUE THREAD

**Issue by medivh-xp** [openxla/xla#20125]
I enabled xla in tf.function and found that the XLA HLO had completed fusion and optimization such as DCE, and then called compile_module_to_llvm_ir to convert it to llvm ir. It seems that the MLIR HLO was not used?

**Comment by akuegel** [comment]
When coming from Tensorflow, we don't go through MHLO, but go to HLO directly. But we use MLIR for the fusion codegen, and for that we at least use the mapping from MHLO to arith/math/complex dialects. So while we never materialize MHLO, it is still indirectly being used.

**Comment by jinjidejinmuyan** [comment]
> When coming from Tensorflow, we don't go through MHLO, but go to HLO directly. But we use MLIR for the fusion codegen, and for that we at least use the mapping from MHLO to arith/math/complex dialects. So while we never materialize MHLO, it is still indirectly being used.

I have the same question as the original poster. By examining the source code of the RunBackend() function in /xla/xla/service/gpu/gpu_compiler.h, I found that the CompileModuleToLlvmIr() function is used to directly lower the HloModule to LLVM IR, without involving MLIR. In the source code, I only found the HLOToStableHLO() method, but it does not return an executable similar to an Executable, and I couldn't find a method like Compile() that calls this method. Could you please explain how XLA transitions into MLIR, and in which file can the entire compilation flow be found?

**Comment by medivh-xp** [comment]
> When coming from Tensorflow, we don't go through MHLO, but go to HLO directly. But we use MLIR for the fusion codegen, and for that we at least use the mapping from MHLO to arith/math/complex dialects. So while we never materialize MHLO, it is still indirectly being used.

https://openxla.org/stablehlo/roadmap In xla's roadmap I saw that MHLO will be deprecated and hardware-independent optimizations will be moved to StableHLO. I want to understand the background of this. It seems that MLIR is no longer considered an infrastructure in XLA?

**Comment by akuegel** [comment]
> > When coming from Tensorflow, we don't go through MHLO, but go to HLO directly. But we use MLIR for the fusion codegen, and for that we at least use the mapping from MHLO to arith/math/complex dialects. So while we never materialize MHLO, it is still indirectly being used.
> 
> I have the same question as the original poster. By examining the source code of the RunBackend() function in /xla/xla/service/gpu/gpu_compiler.h, I found that the CompileModuleToLlvmIr() function is used to directly lower the HloModule to LLVM IR, without involving MLIR. In the source code, I only found the HLOToStableHLO() method, but it does not return an executable similar to an Executable, and I couldn't find a method like Compile() that calls this method. Could you please explain how XLA transitions into MLIR, and in which file can the entire compilation flow be found?

If you dig deeper, you can see that `ir_emitter->EmitHloComputation()` does the codegen for the individual HloInstructions. For kFusion instruction, the MLIR-based fusion emitters will be used. It is a lowering pipeline that does not directly lower to LLVM IR, but with several intermediate representations. The fusion codegen can be found in the `fusions` subfolder of gpu.

**Comment by jinjidejinmuyan** [comment]
> > > When coming from Tensorflow, we don't go through MHLO, but go to HLO directly. But we use MLIR for the fusion codegen, and for that we at least use the mapping from MHLO to arith/math/complex dialects. So while we never materialize MHLO, it is still indirectly being used.
> > 
> > 
> > I have the same question as the original poster. By examining the source code of the RunBackend() function in /xla/xla/service/gpu/gpu_compiler.h, I found that the CompileModuleToLlvmIr() function is used to directly lower the HloModule to LLVM IR, without involving MLIR. In the source code, I only found the HLOToStableHLO() method, but it does not return an executable similar to an Executable, and I couldn't find a method like Compile() that calls this method. Could you please explain how XLA transitions into MLIR, and in which file can the entire compilation flow be found?
> 
> If you dig deeper, you can see that `ir_emitter->EmitHloComputation()` does the codegen for the individual HloInstructions. For kFusion instruction, the MLIR-based fusion emitters will be used. It is a lowering pipeline that does not directly lower to LLVM IR, but with several intermediate representations. The fusion codegen can be found in the `fusions` subfolder of gpu.

Thank you for your patient explanation and valuable suggestions.
I found the corresponding code and understood the principles involved. However, I have another question: what role does StableHLO play in this context? I noticed that in the CreateMLIRModule() function in xla/xla/service/gpu/fusions/mlir/mlir_fusion_emitter.cc, only the MHLO dialect is registered, and the StableHLO dialect is not. Additionally, I found that in the Compile() function in xla/xla/client/client.h, the input to the function is actually an HloModule. I understand that the Compile() function should be an entry point. Therefore, the entire IR chain appears to be: HLO -> MLIR (various dialects including MHLO) -> LLVM IR, with no mention of StableHLO. This makes me wonder what the current role of StableHLO in XLA is. (Is it because the work of replacing MHLO with StableHLO is not yet complete, so it's still using MHLO, and will later be replaced with StableHLO?)

Another question I'd like to ask is about the hierarchical relationship between XLA HLO and the StableHLO dialect. In future OpenXLA work, what will the IR lowering relationship be? Will it be XLA HLO -> MLIR (various IR dialects, including StableHLO) -> LLVM IR? If not, could you explain the lowering strategy?

Lastly, how does XLA support dynamic compilation? In my understanding, HLO does not have the capability to express dynamic shapes, but MLIR does support dynamic shapes. If the lowering strategy is HLO -> MLIR, and if HLO cannot express dynamic shape semantics, then MLIR would not receive dynamic shape information. So, I'm quite puzzled about how XLA supports dynamic shapes.

I would appreciate your help in clarifying these questions.

**Comment by akuegel** [comment]
> Thank you for your patient explanation and valuable suggestions. I found the corresponding code and understood the principles involved. However, I have another question: what role does StableHLO play in this context? I noticed that in the CreateMLIRModule() function in xla/xla/service/gpu/fusions/mlir/mlir_fusion_emitter.cc, only the MHLO dialect is registered, and the StableHLO dialect is not. Additionally, I found that in the Compile() function in xla/xla/client/client.h, the input to the function is actually an HloModule. I understand that the Compile() function should be an entry point. Therefore, the entire IR chain appears to be: HLO -> MLIR (various dialects including MHLO) -> LLVM IR, with no mention of StableHLO. This makes me wonder what the current role of StableHLO in XLA is. (Is it because the work of replacing MHLO with StableHLO is not yet complete, so it's still using MHLO, and will later be replaced with StableHLO?)

Currently, StableHLO is the entry point for example for JAX. StableHLO is then transformed to HLO, and (at least for now) not used again. There is some talk about whether we can use StableHLO instead of MHLO when we go from HLO to the various MLIR dialects, but nothing specific yet.

> Another question I'd like to ask is about the hierarchical relationship between XLA HLO and the StableHLO dialect. In future OpenXLA work, what will the IR lowering relationship be? Will it be XLA HLO -> MLIR (various IR dialects, including StableHLO) -> LLVM IR? If not, could you explain the lowering strategy?

I don't know so much about the future, but at least currently the relationship between XLA HLO and StableHLO (concerning the GPU backend which you seem to be interested about) is that StableHLO is kind of a wrapper around XLA HLO to offer some backward compatibility. Stablehlo is (at least for now) not involved in the lowering pipeline.

> Lastly, how does XLA support dynamic compilation? In my understanding, HLO does not have the capability to express dynamic shapes, but MLIR does support dynamic shapes. If the lowering strategy is HLO -> MLIR, and if HLO cannot express dynamic shape semantics, then MLIR would not receive dynamic shape information. So, I'm quite puzzled about how XLA supports dynamic shapes.
> 
> I would appreciate your help in clarifying these questions.

XLA only has limited dynamic shapes support. You can use dynamic padder which allows you to specify which dimensions are considered dynamic, but you pass a static upper bound for those dynamic dimensions. I am not sure how much this is actually used on GPU, just recently I fixed a bug related to that which has been around for quite some time.

**Comment by medivh-xp** [comment]
It also solved my doubts. Thank you both for your wonderful discussion ：）.
