### ISSUE TITLE
JAX built against XLA crashes on Pascal GPUs in WSL after commit 16e953a921c150dcaf012299a52d771e4bb425c2

### ISSUE THREAD

**Issue by terafo** [openxla/xla#2249]
I've encountered an issue where JAX built against XLA crashes on Pascal GPUs while running under Windows Subsystem for Linux (WSL). This issue seems to have started after the recent commit 16e953a921c150dcaf012299a52d771e4bb425c2.

### Environment
XLA commit: 16e953a921c150dcaf012299a52d771e4bb425c2
JAX commit: ae4f1fcb66d13d6606525c0810bd9a0aba087f0c
GPU: I confirmed that it happens on 1060 and 1080 Ti
WSL version: 1.1.6.0
Ubuntu version: Ubuntu 22.04.2 LTS
NVIDIA driver version: 531.41
CUDA toolkit version: 11.8
cuDNN version: 8.8.1

### Steps to reproduce:
Install latest version of Jax.
With CUDA 11:
```python
jax.random.normal(jax.random.PRNGKey(0),(5,5))
```
With CUDA 12:
Example with CUDA 11 and, in addition, any attempt to create an array.
```python
jax.numpy.zeros((5,5))
```
I also created issue in jax repo with this issue https://github.com/google/jax/issues/15260

**Comment by tpopp** [comment]
Hello, XLA's support is generally either:
1. Welcoming contributions
2. Supporting platforms that have been supported by Tensorflow or JAX. It looks like JAX does not support it, and Tensorflow only promises support for WSL2, so those would be two ways to bring it up, otherwise, there is not an existing team that I'm aware of that would fix this freely.

**Comment by tpopp** [comment]
Marking as wontfix but leaving the issue open in case it is still happening in other situations or for others to jump in.

**Comment by akuegel** [comment]
This should have been fixed by the revert: https://github.com/openxla/xla/commit/30cffde8755496ec524e3973b9c12ae247616b34
