### ISSUE TITLE
Could not find any nvml.h for cuda docker container in XLA? 

### ISSUE THREAD

**Issue by i-chaochen** [openxla/xla#6923]
It seems there are something changes in recent cuda docker image.

I followed all instructions here https://github.com/openxla/xla/blob/main/docs/build_from_source.md

`tensorflow/tensorflow:devel-gpu` and it cannot compile due to 

<img width="425" alt="image" src="https://github.com/openxla/xla/assets/913790/773a4f70-43b0-48f4-881a-eb39f94ae99f">

I have tried ```gcr.io/tensorflow-sigs/build:latest-python3.9``` and it's same result.

May I ask which docker image is for cuda test?

**Comment by cheshire** [comment]
@Artem-B WDYT?

**Comment by Artem-B** [comment]
Where do TF's dockerfiles live? That may help figuring out what's changed recently.

As for debugging it in general, I'd start by checking whether the missing file is  present in the container or not. That would narrow down the source of the problem to TF build (if the file is there, but not found because the build is broken) or the file is missing, and the issue is somewhere in the dockerfile.

**Comment by Artem-B** [comment]
I've found this change that may be related: https://github.com/tensorflow/tensorflow/commit/15232520bba5793ed15e174a737c0d9296dbec30

`cuda-nvml-dev` is probably the package that carries nvml.h
So, check if it's present in the container you're using. If it's not, then it's something TF maintainers may need to fix.

**Comment by i-chaochen** [comment]
Thanks @Artem-B 

After I installed ```cuda-nvml-dev``` (https://packages.ubuntu.com/focal/libnvidia-ml-dev) and it works now.

But still I think the offical document or CI docker container need to update with this package.

**Comment by Artem-B** [comment]
Looks that way. @cheshire -- who's in charge of the official docker images these days?

**Comment by Micky774** [comment]
Wanted to check if this was still being addressed, as I also hit this speedbump 😅
