### ISSUE TITLE
Nondeterminism in triton-autotuner and others leads to hangs in multi-process gpu execution

### ISSUE THREAD

**Issue by trevor-m** [openxla/xla#7716]
Opening an issue to help us keep track of this even though the discussion has already been ongoing elsewhere.

When using multi-process execution, XLA compiles each module indepedently for each process. Nondeterministic passes like `triton-autotuner` can produce different results per process, which can lead to different optimizations happening later down the pipeline. If any of those optimizations leads to a different ordering of collectives in the schedule, or a different `is_async` designation for collectives, then there will be deadlocks on the first execution.

The ideal solution would be to compile the module once and broadcast the result to all other processes. I believe @hawkinsp is currently planning to work on this.

**Comment by cheshire** [comment]
@PatriosTheGreat is looking into it.

**Comment by PatriosTheGreat** [comment]
The fix was submitted to JAX: https://github.com/google/jax/commit/9a098e922aff62a3b49bd673b9518d97ee599248
It adds 2 new optional flags (turned-off by default):

1. jax_share_binary_between_hosts: if flag is enabled the coordinator process (the process with id 0) will share the optimized module with other processes. This will not work if the module contains host callbacks and it might overuse networking since one process will send modules one-by-one to all participants.
2. jax_share_autotune_config_between_hosts: if flag is enabled the coordinator process will share only autotune config with other participants. This flag will increase compilation time by ~1.5x since each participant would need to wait for the coordinator process to compile the module and then compile it again. 

These flags can be combined and then  jax_share_binary_between_hosts will be used for modules without host callbacks, otherwise jax_share_autotune_config_between_hosts will be used.

**Comment by cheshire** [comment]
Great ! Would be amazing if we could get to the on-by-default solution.

**Comment by PatriosTheGreat** [comment]
After https://github.com/openxla/xla/commit/2500111022fc9791bd9134134258c2606be50c4d autotune shard should be enabled by default.
This flag should fix an original issue.

Thanks @sergachev for implementing autotune sharding!
